### PR TITLE
Fix passing props when executing script

### PR DESCRIPTION
**Pull request by adbario**
## Description

https://github.com/onflow/flow-js-testing/pull/186 Fixes the scoping issue of transaction props, but this needs to be done for executing the scripts as well. Executing scripts using the bundle won't work without the fix, so would be great to have a new release once this gets merged.

These bundle-related issues can't be seen by running the test suite, as the tests use the source code.

---

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-js-testing/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation - **no relevant documentation**
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by adbario** [comment]
@justinbarry Mind looking at this when you have a moment, as executing scripts is currently blocked on the latest version?

Thanks 👍

**Comment by jribbink** [comment]
I'm 99% sure that simply merging this PR should fix #191 & #182 as well. @gregsantos

**Comment by adbario** [comment]
> I'm fairly certain that simply merging this PR should fix #191 & #182. @gregsantos

Yes, both of those issues should be solved by this.

Would be great to have PRs https://github.com/onflow/flow-js-testing/pull/177 and https://github.com/onflow/flow-js-testing/pull/188 as well merged at some point to solve couple of deprecation warnings.

**Comment by gregsantos** [comment]
Thanks folks, will try to get these reviewed and merged asap

**Review by gregsantos — APPROVED** [review]
Thanks for this, looks good

**Pull request merged**
