### PR TITLE
resolve outdated import of flow-cadut/generator

### PR DESCRIPTION
**Pull request by y1cunhui**
Closes #???

## Description

---

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-js-testing/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Review by justinbarry — APPROVED** [review]
LGTM

**Comment by gregsantos** [comment]
@justinbarry Can you merge this if g2g?

**Comment by adbario** [comment]
@gregsantos This seems to be fixed already in https://github.com/onflow/flow-js-testing/pull/192

**Comment by gregsantos** [comment]
Right on, thanks @adbario looks like it! Thanks for your contribution @y1cunhui! Going to close this

**Pull request closed without merging**
