### PR TITLE
Add FUSD

### LINKED ISSUE #17: Methods and examples showcasing usage of FUSD
Create methods and examples showcasing usage of FUSD contract.

### PR DESCRIPTION
**Pull request by adhurjaty**
Closes #17 

## Description

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-js-testing/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by kerrywei** [comment]
> Thank you for opening this PR @adhurjaty I will give it a look later today and get back to you if I find anything ;)

@MaxStalker 
do we want to enforce the writing test plans in this repo? if so we should update the template to reflect this and reminder contributors

**Comment by MaxStalker** [comment]
@kerrywei that would be great! This should also speed up the process of PR acceptance.

**Comment by justinbarry** [comment]
@adhurjaty FUSD has been more or less deprecated. Any thoughts on migrating this PR to USDC?

**Comment by bluesign** [comment]
maybe let's make this generic to any FungibleToken somehow, who knows if there will be USDC after 5months

**Pull request closed without merging**
