### PR TITLE
replace docs with links

### PR DESCRIPTION
**Pull request by nialexsan**
Closes #???

## Description

replaces docs content with links to their new location in https://github.com/onflow/docs
using script from https://github.com/onflow/docs/pull/46/files#diff-c664086afba767b573a654a57f324cee7c36fe1e9b7a1a02627c642577897871

---

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-js-testing/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Review by bthaile — APPROVED** [review]
lgtm

**Comment by MaxStalker** [comment]
I don't believe this is for the best...
You can source docs from different place to utilize in developers portal, but there are no benefits for contribution on this repo. One will need to create separate PR on a different repo to sync updates to new API/changes 🤷‍♂️

**Comment by nialexsan** [comment]
@MaxStalker I fully understand your concern, but we've tried sourcing docs from different repos. The number of cross-reference links makes it extremely difficult to maintain and make sure that everything is working.

we've rolled these changes across other repos already

overall it already decreased the maintenance effort and creating a separate PR to https://github.com/onflow/docs seemed to be a reasonable trade-off

Let me know what you think regarding this, I'm open for a discussion

**Comment by MaxStalker** [comment]
Well, let's give it a try 😁

**Review by MaxStalker — APPROVED** [review]

**Pull request merged**
