### PR TITLE
adapt library for cadence1

### LINKED ISSUE #224: Stable Cadence preview release support
## Description

With the Stable Cadence milestone approaching (Cadence 1.0) and preview releases of Flow CLI, emulator, flow-go SDK, etc. enabling devs to compose next version Cadence code, developers will need to be able to test their updated implementations using existing tests.

## Suggestion

This testing framework is often used across many Flow projects, including standard and core repos - flow-nft, nft-storefront, flow-core-contracts to name a few. It would be very helpful to run the same tests passing with a current Cadence version against an updated Cadence 1.0 implementation using a flow-js-testing pre-release.

## Context

Working on [stable cadence updates](https://github.com/onflow/nft-storefront/pull/89) to the NFTStorefront contracts and will continue to update contracts moving forward.

### PR DESCRIPTION
**Pull request by NtTestAlert**
Closes #224

## Description

Various changes to support Cadence 1.0 emulator
All tests are passing

I've changed the workflow to use Cadence 1.0 CLI
This will need to be reverted later on

---

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-js-testing/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Comment by jribbink** [comment]
Hey @NtTestAlert , thanks for the PR! I will review this & try to release it today :)

**Comment by NtTestAlert** [comment]
> Hey @NtTestAlert , thanks for the PR! I will review this & try to release it today :)

Hi, there is one more thing to be done, stable-cadence cli adds `-c1` suffix (but only in some versions), and a version check in general would be good.
Will add it in soon.

**Comment by NtTestAlert** [comment]
Added execName param to emulator, defaulting to flow-c1
tested locally with older flow-cli, as new ones don't run on windows

**Comment by jribbink** [comment]
I tried getting CI to work, but I'm having issues so I guess I can just run locally toverify.

I just ran the tests and it looks good, but it seems like signer parsing fails for an entitled account reference as a signer (e.g. `auth(SaveValue) &Account` as oppose to an unauthorized reference `&Account`), which is generally speaking what users will be using in their transactions.

Are we able to support this?  Seems like it might be a blocker for any real usage of the library?

**Comment by NtTestAlert** [comment]
The tests for flow-js-testing pass, incl those with authorized signers - it doesn't try to parse them before executing
However flow-cadut does not properly parse authorized signers as per other PR, added a fix there.

Pipeline failed because it could not parse version due to the upgrade banner, bypassed by adding --output json to "fool" flow-cli

**Comment by NtTestAlert** [comment]
Still need to adapt the library to work with shorthand imports
(`import "ViewResolver"`)
In my project I have this hooked in jest and with some regexes that expand it to `import ViewResolver from "./ViewResolver.cdc"`
I'll try to add it to the library today

**Review by jribbink — APPROVED** [review]
Awesome!! I've brought this up to date with the latest `@onflow/flow-cadut@stable-cadence` release & will merge this, release -> `@onflow/flow-js-testing@stable-cadence`.  Thank you for your contribution!

**Pull request merged**
